version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine3.20
    container_name: bigmeter_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-bigmeter}
      TZ: Asia/Bangkok
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Port not exposed - internal Docker network only
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  migrate:
    image: postgres:17.5-alpine3.20
    container_name: bigmeter_migrate
    profiles: ["setup"]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATABASE: ${POSTGRES_DB:-bigmeter}
      TZ: Asia/Bangkok
    volumes:
      - ./migrations:/migrations:ro
    command: ["sh", "-c", "set -e; for f in /migrations/*.sql; do echo Running $$f; psql -v ON_ERROR_STOP=1 -f $$f; done"]
    restart: "no"

  seed_branches:
    image: postgres:17.5-alpine3.20
    container_name: bigmeter_seed_branches
    profiles: ["setup"]
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATABASE: ${POSTGRES_DB:-bigmeter}
      TZ: Asia/Bangkok
    volumes:
      - ./seed-data:/seed:ro
    command:
      - sh
      - -c
      - |
          set -e
          psql -v ON_ERROR_STOP=1 <<'SQL'
          CREATE TEMP TABLE IF NOT EXISTS _seed_b (
            ba_code text, branch_code text, ba_code_dup text, name text, region_id text, region_code text
          );
          \copy _seed_b FROM '/seed/r6_branches.csv' CSV HEADER;
          INSERT INTO bm_branches (code, name)
          SELECT DISTINCT TRIM(ba_code), TRIM(name) FROM _seed_b
          ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name;
          SQL
    restart: "no"

  api:
    image: ${DOCKER_REGISTRY:-your-registry}/bigmeter-api:${IMAGE_TAG:-latest}
    container_name: bigmeter_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DSN: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-bigmeter}?sslmode=disable
      TIMEZONE: ${TIMEZONE:-Asia/Bangkok}
      BRANCHES: ${BRANCHES:-}
      PORT: ${PORT:-8089}
    ports:
      - "8089:8089"
    restart: unless-stopped

  sync:
    image: ${DOCKER_REGISTRY:-your-registry}/bigmeter-sync:${IMAGE_TAG:-latest}
    container_name: bigmeter_sync
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ORACLE_DSN: ${ORACLE_DSN:-}
      POSTGRES_DSN: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-bigmeter}?sslmode=disable
      TIMEZONE: ${TIMEZONE:-Asia/Bangkok}
      BRANCHES: ${BRANCHES:-}
      MODE: ${MODE:-}
      SYNC_CONCURRENCY: ${SYNC_CONCURRENCY:-2}
      SYNC_RETRIES: ${SYNC_RETRIES:-2}
      SYNC_RETRY_DELAY: ${SYNC_RETRY_DELAY:-10s}
      BATCH_SIZE: ${BATCH_SIZE:-100}
      ENABLE_YEARLY_INIT: ${ENABLE_YEARLY_INIT:-true}
      ENABLE_MONTHLY_SYNC: ${ENABLE_MONTHLY_SYNC:-true}
      METRICS_ADDR: ${METRICS_ADDR:-}
    ports:
      - "${METRICS_PORT:-9090}:9090"
    restart: unless-stopped

  frontend:
    image: ${DOCKER_REGISTRY:-your-registry}/bigmeter-frontend:${IMAGE_TAG:-latest}
    container_name: bigmeter_frontend
    depends_on:
      - api
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  pgdata:
